server: 
  port: 8080
  
spring:
  application:
    name: spring-boot-dubbo-service

dubbo:
  application:
    name: spring-boot-dubbo-service
  registry:
    address: zookeeper://127.0.0.1:2181 #zookeeper://10.1.51.248:2181
  protocol:
    name: dubbo
    port: 20880
  scan: com.lksoulman.service

#debug: true